name: Docker push and create github release

on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with 'v' (e.g., v1.0.0)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Steps to build and push Docker image
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t fcolista/apkfile:${{ steps.get_version.outputs.VERSION }} .
          docker push fcolista/apkfile:${{ steps.get_version.outputs.VERSION }}

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-push  # Ensure this job runs after build-and-push

    steps:
      # Steps to create a GitHub release
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          generate_release_notes: true
